package tests_divers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class CreateBase 
{

	private Connection local;
	private Statement localStat;

	/*
	 * Table 
	 */
	
	public CreateBase() 
	{
		try 
		{			
			local = DriverManager.getConnection("jdbc:hsqldb:file:SSFIV", "sa", "");
			localStat = local.createStatement();			
		} 
		catch(Exception e) 
		{			
			e.printStackTrace();			
		}	
	}
	
	public void create() 
	{
		try 
		{
			String requete;
			
			requete = "CREATE TABLE Fighters " +
						"(" +
						"fighter_id numeric(2) NOT NULL, " +
						"fighter_name varchar(20), " +
						"PRIMARY KEY (fighter_id)" +
						")";
			localStat.executeUpdate(requete);
			
			requete = "CREATE TABLE SpecialMoves " +
						"(" +
						"move_id INTEGER GENERATED BY DEFAULT AS IDENTITY, " +
						"fighter_id numeric(2) NOT NULL, " +
						"move_name varchar(50), " +
						"move_input varchar(25), " +
						"move_type char(1), " +
						"move_armor_break boolean, " +
						"move_ex_possible boolean, " +
						"move_note varchar(100), " +
						"PRIMARY KEY (move_id), " +
						"FOREIGN KEY (fighter_id) REFERENCES Fighters(fighter_id)" +
						")";
			localStat.executeUpdate(requete);
			
			requete = "CREATE TABLE FrameData " +
						"(" +
						"move_id INTEGER GENERATED BY DEFAULT AS IDENTITY, " +
						"fighter_id numeric(2) NOT NULL, " +
						"move_name varchar(50), " +
						"move_input varchar(25), " +
						"move_type char(1), " +
						"move_damage varchar(25), " +
						"move_block varchar(2), " +
						"move_stun varchar(25), " +
						"move_meter varchar(25), " +
						"move_startup varchar(25), " +
						"move_active varchar(25), " +
						"move_recovery varchar(25), " +
						"move_hit_adv varchar(25), " +
						"move_block_adv varchar(25), " +
						"move_iframes varchar(25), " +
						"move_chain boolean, " +
						"move_special boolean, " +
						"move_super boolean, " +
						"move_note varchar(100), " +
						"PRIMARY KEY (move_id), " +
						"FOREIGN KEY(fighter_id) REFERENCES Fighters(fighter_id)" +
						")";
			localStat.executeUpdate(requete);
		} 
		catch(Exception e) 
		{
			e.printStackTrace();
		}
	}
	
	public void insert()
	{
		try
		{
			localStat.executeUpdate("INSERT INTO Fighters values ('1','Ryu')");
			localStat.executeUpdate("INSERT INTO SpecialMoves values(NULL,'1','Hadoken','236P','s','false','true','')");
			localStat.executeUpdate("INSERT INTO SpecialMoves values(NULL,'1','Shoryuken','623P','s','false','true','')");
			localStat.executeUpdate("INSERT INTO SpecialMoves values(NULL,'1','Tatsumaki Senpukyaky','214K','s','true','true','')");
			localStat.executeUpdate("INSERT INTO SpecialMoves values(NULL,'1','Airborne Tatsumaki Senpukyaku','214K','s','false','true','PR En lair')");
			localStat.executeUpdate("INSERT INTO SpecialMoves values(NULL,'1','Shinku Hadoken','236236P','S','false','false','')");
			localStat.executeUpdate("INSERT INTO SpecialMoves values(NULL,'1','Metsu Hadoken','236236PPP','U','false','false','')");
			localStat.executeUpdate("INSERT INTO SpecialMoves values(NULL,'1','Metsu Shoryuken','236236KKK','U','true','false','')");
			localStat.executeUpdate("INSERT INTO SpecialMoves values(NULL,'1','Shoulder Throw','6|NLPK','t','false','false','PR prés adversaire')");
			localStat.executeUpdate("INSERT INTO SpecialMoves values(NULL,'1','Somersault Throw','4LPK','t','false','false','PR prés adversaire')");
			localStat.executeUpdate("INSERT INTO SpecialMoves values(NULL,'1','Collarbone Breaker','6MP','u','false','false','')");
			localStat.executeUpdate("INSERT INTO SpecialMoves values(NULL,'1','Solar Plexus Strike','6FP','u','false','false','')");
		}
		catch(SQLException e)
		{
			e.printStackTrace();
		}
	}
	
	public void close() throws Exception 
	{
		localStat.execute("SHUTDOWN");
		localStat.close();
	}
	
}
